### PR TITLE
homepage includes navbar carousel login form donor list etc

### PR DESCRIPTION
**Pull request by webpagearshi**

### CODE REVIEW

**Comment by webpagearshi** [comment]
https://webpagearshi.github.io/jeevan-rakht/public/index.html

**Comment by utkarsh2102** [comment]
Hi @webpagearshi,
These changes looks good to me.
I can't exactly comment if it matches the Layout the team has decided or not but I really appreciate this work of yours.
@gauravsinghaec @strongSoda @viditkothari @Soumya44 
Please review these changes and take your action accordingly. 

Also, @webpagearshi please resolve the Merge Conflicts.

**Comment by mcashashankkumar** [comment]
Hi @webpagearshi,
Its look great!!, I really appreciate you hard work and dedication towards this project, 
i will waiting for other reviewers
@gauravsinghaec @strongSoda @viditkothari @Soumya44
after that we will update instructions.

**Comment by MorphyMeri** [comment]
Add some black colour to the images with little opacity so that if we put any text it is visible

**Comment by webpagearshi** [comment]
Hi friends,am a bit confused as to what I should do next.Shall I wait for all the reviews?Also I am bit new to github so will need a bit of help to resolve merge conflicts.Thanks, Utkarsh and Shashank.

**Comment by utkarsh2102** [comment]
Hi @webpagearshi,
I'm afraid that I'll have to close this PR since there's no activity on this PR.
Need not worry, if there's something genuine which was holding you up, I'll reopen this again and you can fix the changes ASAP.
Let me know if you're willing to take this up.

**Pull request closed without merging**
