### PR TITLE
added image file

### PR DESCRIPTION
**Pull request by priyankajune**
#37
Fix issue-1
Added image file for banner in public/assets/image folder with name img1 and extension .jpeg
Fork link
https://github.com/priyankajune/jeevan-rakht

### CODE REVIEW

**Comment by viditkothari** [comment]
@priyankajune Hi! Is this pull request just for the (unedited / not-worked-upon) image?

**Comment by utkarsh2102** [comment]
Hi @priyankajune,
I'm afraid that we can't accept a PR with no original work in it.
Please use https://www.canva.com/ if you're willing to take #37.
Let us know your update regarding the same.
Meanwhile, I'm closing this. Please open a new PR with your original editing. 
Looking forward for the same.

**Comment by priyankajune** [comment]
Okay @utkarsh2102. Actually i thought i have to put only images for banner.
I have my exams going on,  I will make a new pr after that. 
Thanks!

**Comment by utkarsh2102** [comment]
Sure @priyankajune. Looking forward for your participation.

**Pull request closed without merging**
