### PR TITLE
Implementation - Locate state

### PR DESCRIPTION
**Pull request by crisner**
Implemented code for locate blood state A.
- HTML
- CSS
- minor bootstrap jQuery implementation

[View page](https://crisner-jeevan-rakht.herokuapp.com/locate)

@viditkothari

### CODE REVIEW

**Comment by viditkothari** [comment]
@crisner Nice work! There are some subtle changes though
1) center the JeevanRakht logo
2) Why did you implement the login/signup at the top / header? There was no such thing in our UI design
3) The back / left arrow is too small

**Comment by viditkothari** [comment]
@gauravsinghaec is it ok for you?

**Comment by creatorisback** [comment]
@viditkothari merge my branch first as i have made changes in the header file as directed by you and we are importing header file everywhere so first two issues will be resolved automatically

**Comment by viditkothari** [comment]
@crisner, i have to close this PR and I request you all to only send PR after one of us has successfully reviewed your work on Slack.
Thanks

**Pull request closed without merging**
