### PR TITLE
 i added five text cards 

### PR DESCRIPTION
**Pull request by geetanjali195**
i added text cards to mach with given mock-up..  here is the Ghpage link https://geetanjali195.github.io/jeevan-rakht/public/newindex2.html

### CODE REVIEW

**Comment by geetanjali195** [comment]
designed UI for page not found error! and this is my gh-page url 
https://geetanjali195.github.io/jeevan-rakht/public/page404error.jpg

**Comment by geetanjali195** [comment]
i tried to write java script  code with html for user validation form here is the gh-pg link 
https://geetanjali195.github.io/jeevan-rakht/public/uservalidation.html
and i also tried javascript code with html for change password implementation.. and i have some doubts regarding this..  here is the link
https://geetanjali195.github.io/jeevan-rakht/public/changepassword.html

**Comment by utkarsh2102** [comment]
@gauravsinghaec @strongSoda @viditkothari : Please review this PR and take the required decision.
There are a lot of files and commits to follow.

**Comment by viditkothari** [comment]
I didn't find this PR's signup form or 404 page good for Pull.

@gauravsinghaec @sujan-patel , if you guys find anything worthwhile with the back-end and validation code that @geetanjali195 has made, then do the needful, else I request you to please close this PR

**Comment by viditkothari** [comment]
Hey @geetanjali195 , we may not accept this pull request as the design isn't aligned with our persona. We look forward to your contribution in following issues though.

Happy coding!

**Pull request closed without merging**
