### PR TITLE
three images added in public folder

### PR DESCRIPTION
**Pull request by nehavatsyan**

### CODE REVIEW

**Comment by utkarsh2102** [comment]
What are they for

**Comment by nehavatsyan** [comment]
hi @utkarsh2102 
initially issue number 1 was open for images of banners therefore i created and edited some images. but now i guess you have closed it

**Comment by utkarsh2102** [comment]
Oh well, right.
I closed that because there was a surplus of these images.
Anyways, I'll merge them.
But can you also make this same PR at : https://github.com/utkarsh2102/GoogleUdacity_JeevanRakht
Make a PR there and then ping here. I'll merge both of them.

**Comment by nehavatsyan** [comment]
i have made PR on other one too.

**Comment by utkarsh2102** [comment]
Okay, thank you :D

**Pull request merged**
