### PR TITLE
optimized images for jeevan rakht

### PR DESCRIPTION
**Pull request by meghathedesigner**

### CODE REVIEW

**Comment by meghathedesigner** [comment]
I have added optimized images for Jeevan Rakht its in the asset folder and all the images are named optimized in the beginning so you will identify easily.

**Comment by viditkothari** [comment]
Hi @meghathedesigner 
Thanks for these :)

Few of these are so apt, but there are some important edits without which I cannot use these suitably well and give these the value they deserve.

- Optimized-img_1 : Please check if the canvas area / the image size fits the dimension set for the slider that we have designed, failing which this will get cropped and thus will not look so good.
- Optimized-img_2: Again, please check the dimension
- Optimized-logo2: Needs to be in proper dimension and this seems to be freepik.com. Please fix it.
- need.png: Nice! but may we have some well placed caption?
- Optimized-banner_1 : A nice caption will add such a nice effect to this :)

Looking forward to hearing from you.

Thank you so much for your appreciable effort @meghathedesigner  :)

**Comment by strongSoda** [comment]
@meghathedesigner see if you can get something on the lines of what's suggested by @vidit.

**Comment by meghathedesigner** [comment]
Ok I will :)

**Comment by gauravsinghaec** [comment]
@viditkothari we will be needing different resolution images having max as you suggested. Again we will resize based on viewport size and actual rendering size. (That I can do but let see what Megha is presenting)
@meghathedesigner may I know the file sizes and resolution and did you do any quality compromise while optimizing images. Also please check the below links if you are interested in HTML rendering that I referred above.
**Srcset and Sizes**
http://ericportis.com/posts/2014/srcset-sizes/
**Responsive Images**
https://dev.opera.com/articles/responsive-images/
**The magic of <picture> element from HTML5**
https://www.html5rocks.com/en/tutorials/responsive/picture-element/

**Comment by viditkothari** [comment]
@strongSoda you tagged `vidit` not `viditkothari` 😆

**Comment by meghathedesigner** [comment]
@gauravsinghaec Firstly, thanks for the links you have provided they are really informative :)...Secondly, my first concern is on quality of images, I have not compromised over quality for any of the images for Jeevan Rakht but yes I have followed SEO standard and reduce image sizes.

**Comment by utkarsh2102** [comment]
@meghathedesigner any ETA on this?

**Comment by meghathedesigner** [comment]
@gauravsinghaec sure. :) 
@utkarsh2102 Today I will before 12 A.M

**Comment by gauravsinghaec** [comment]
Thanks a lot, @meghathedesigner. It's indeed before 12 :-)
@viditkothari please check/merge and share your comment so that these images can be included in HTML.

**Comment by meghathedesigner** [comment]
I told you guys it will be done before 12 :) Yo

**Comment by gauravsinghaec** [comment]
@meghathedesigner @viditkothari 😆. haha 11:59

**Pull request merged**
