### PR TITLE
Added new images, Changes made as per wire-frame and added animation

### PR DESCRIPTION
**Pull request by meghathedesigner**
Made changes in index.html page. added new css, new images, new icons. For animation added animate.css and Wow.js
Scope: index.html
Added: Images, animate.css, Wow.js

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @meghathedesigner,
Please provide me a link to your hosted GitHub page. Else the changes can't be seen otherwise.

**Comment by meghathedesigner** [comment]
Ok can you please tell the process to do it... to add gh pages i will do that :)

**Comment by utkarsh2102** [comment]
Sure @meghathedesigner. I'll message you on Slack.

**Comment by utkarsh2102** [comment]
Hi @meghathedesigner,
As discussed, I'm closing this PR. I hope the new one is coming today?
Hope to see one real soon.
If there's any issue regarding this, feel free to contact. I'll reopen this again.
Thank you for contributing. Looking forward for more participation.

**Comment by meghathedesigner** [comment]
Ya sure

**Pull request closed without merging**
