### PR TITLE
jeevan-rakht

### PR DESCRIPTION
**Pull request by Sunnypaul393**
Designed UI-Sign-Up page

### CODE REVIEW

**Comment by Sunnypaul393** [comment]
Can I send you a snapshot since I made the changes in my system. I didnt
actually link it in github.

**Comment by strongSoda** [comment]
U can host ur post on ur fork s gh pages and then send PR . Website is better to review than a snapshot.

**Comment by Sunnypaul393** [comment]
Actually i tried that i gdt 404 error

**Comment by strongSoda** [comment]
Add relative path at the end of ur link to navigate to index.html in public folder.

Just add public/index.html at the end of ur gh pages url

**Comment by utkarsh2102** [comment]
@gauravsinghaec @strongSoda @viditkothari @Soumya44 @mcashashankkumar : Since I can't read the code for 63 files, I request you to take your decision on this PR.

@Sunnypaul393,
Was there any file you did not change? :laughing:

**Comment by viditkothari** [comment]
@Sunnypaul393 
Please send:
1) Hosted project link OR
2) Screenshot(s) to at least let us see if we need the features / updates that you have implemented.

You have ~3 hours until this PR gets closed.

**Comment by viditkothari** [comment]
@Sunnypaul393 
I've reviewed your request by manually setting up the files and checking out the project. We may not use this implementation.

test111

**Pull request closed without merging**
