### PR TITLE
PR for Issue-3 : App Design to HTML & CSS 

### PR DESCRIPTION
**Pull request by thisisabdus**
here is the live version. 
[http://jeevan-rakht.herokuapp.com/](https://jeevan-rakht.herokuapp.com/app.html)

Feedbacks will be appriciated. Thank you.

### CODE REVIEW

**Comment by thisisabdus** [comment]
@viditkothari would you mind explaining a little bit about what should I change Now? Like, the hover effects, colors or layouts etc.

**Comment by viditkothari** [comment]
@thisisabdus 
1. Fix the animation
2. Issue with the sizing / update-in-size of the button
3. Footer should be of less height
4. Fix the fonts
5. OnHover effect and color needs fixing

**Comment by utkarsh2102** [comment]
@viditkothari, great catch. Please keep a track of this PR.
I'm assigning this PR to you.
@thisisabdus, whenever you fix this in your commit, please ping here.

**Comment by thisisabdus** [comment]
@viditkothari, @utkarsh2102 `fa-hand-holding-heart` isn't rendering. Any alternate icon to replace it?

> 4. Fix the fonts
May I know the name of that font?

**Comment by thisisabdus** [comment]
Done. I fixed some bugs. 

- [ ]  Fix the animation
- [ ] Issue with the sizing / update-in-size of the button
- [ ]  Footer should be of less height
- [ ] Fix the fonts
- [ ] OnHover effect and color needs fixing

**Comment by utkarsh2102** [comment]
@thisisabdus, nice.
But when hovered the size of those 2 divs increases but never goes back to its original position.
Please fix the same.
@viditkothari @strongSoda @mcashashankkumar @gauravsinghaec : Please review the same and add your comments.

**Comment by thisisabdus** [comment]
Fixed @utkarsh2102.

**Comment by thisisabdus** [comment]
@viditkothari Have a look on it

**Comment by utkarsh2102** [comment]
@thisisabdus : The problem still seems to be there.
"When hovered the size of those 2 boxes increases but never goes back to its original position.
Please fix the same."

**Comment by thisisabdus** [comment]
@utkarsh2102 Can you please provide me a gif or video showing where the problem is occuring? Because I couldn't find any issue with box sizing in my PC.

**Pull request closed without merging**
