### PR TITLE
Updated : typo in #184

### PR DESCRIPTION
**Pull request by Logan1x**
Updated typo in signup page.
for issue #184

### CODE REVIEW

**Comment by gauravsinghaec** [comment]
make the placeholder as blood stock(in ltr)

**Comment by Logan1x** [comment]
selection_029
I am not able to see any changes after git squash. when I am running `git status` it says the working tree is clean nothing to commit.

**Comment by gauravsinghaec** [comment]
@Logan1x you need to have your changes in a new branch otherwise you may lose your changes.
Check below links for more info.
**Combining multiple commits into one using git rebase**
https://feeding.cloud.geek.nz/posts/combining-multiple-commits-into-one/
**On undoing, fixing, or removing commits in git**
https://sethrobertson.github.io/GitFixUm/fixup.html
**How to permanently remove few commits from remote branch**
https://stackoverflow.com/questions/3293531/how-to-permanently-remove-few-commits-from-remote-branch?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
**Git revert last commit in heroku**
https://stackoverflow.com/questions/5248103/git-revert-last-commit-in-heroku?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
How do I delete a Git branch both locally and remotely?
https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-both-locally-and-remotely?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by Logan1x** [comment]
I've done squashing but still don't know why there are two commits😅😅

**Comment by Logan1x** [comment]
>you need to have your changes in a new branch 

the changes were already in branch and I didn't select it before that why I was having [issues](https://github.com/UdacityFrontEndScholarship/jeevan-rakht/pull/188#issuecomment-387468232).

**Comment by gauravsinghaec** [comment]
ha ha.. Now it became 6 commits @Logan1x  
Let me help you out with this one. DM me and we will close it by tonight.

**Comment by Logan1x** [comment]
whoops!! done thanks for all of this

**Comment by gauravsinghaec** [comment]
@Logan1x well done and hope you learnt few new things too.

**Comment by Logan1x** [comment]
Yes lot of learning and support from community 😊

**Pull request merged**
