### PR TITLE
Changes in index

### PR DESCRIPTION
**Pull request by Himanshuvashist**
i have made some changes in the Index file . hope its looking better now

### CODE REVIEW

**Comment by Himanshuvashist** [comment]
Here is the preview cheak it out. 

https://himanshuvashist.github.io/jeevan-rakht/public/index.html

**Comment by utkarsh2102** [comment]
@Himanshuvashist,
Also, please give a brief description of the changes you've made in order to review all the sections properly. Edit your upper comment and let me know once done.

**Comment by gauravsinghaec** [comment]
@utkarsh2102 it was so nice of you to go and check the code for changes but yeah we need better description to look into it rather finding ourselves what was the PR about :-)

**Comment by Himanshuvashist** [comment]
I think i have resolved conflicts. @utkarsh2102

**Comment by utkarsh2102** [comment]
Nice @Himanshuvashist. 
@strongSoda @viditkothari @Soumya44 @gauravsinghaec : Please review and merge if it looks good.

**Comment by strongSoda** [comment]
@Himanshuvashist  can u reduxe the number of commits to one?

Also can u remove any of the changes that werent in the parent apart from the changes made by u for this PR.

Imran

**Comment by utkarsh2102** [comment]
@strongSoda : Leave the commit thing this time. He just learnt to resolve conflicts. It'd be a little difficult for him to squash those to 1 now :sweat_smile: 
Also, @Himanshuvashist please take care of the second point @strongSoda made.

**Comment by Himanshuvashist** [comment]
@strongSoda  Bro i do not understand please message me on slack tell me what to do exactly and i will do it then.

**Pull request merged**
