### PR TITLE
#145 Redesigned Footer with the Font Awesome images.

### PR DESCRIPTION
**Pull request by Kundan28**
Redesigned Footer with the Font Awesome images and made some changes in the main.css file for the footer.

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @Kundan28,
This looks nice to me.
Can you please attach a screenshot of the redesigned footer?

**Comment by viditkothari** [comment]
@Kundan28 thank you so much for the effort in cleaning up the footer. I have couple of things to mark and say though:
1 ) I've *never* seen a blood bank be active on GitHub. So we should always make sure that **all the content** in our website / creations of any kind are ** *relevant* **. So we don't need GitHub icon in socials.
2) This website is the blog to the application. So why put Blogger icon?
3) I think you can remove all but FB + Insta + Email icons
4) Before you make any changes, I want to remind you of some design changes we are planning which may not provide value to your time spent updating this.

Instead, I'll suggest you to wait for sometime before we come up with a plan, announce it and then contribute.

Thanks & hope you will understand

**Comment by Kundan28** [comment]
Okay...I can understand...

**Comment by Kundan28** [comment]
@viditkothari  Removing all that icons don't take more than a minute so I am making that changes and making a PR...
But I can understand you are planning of some design changes which may not provide value to my time spent updating this.

**Comment by Kundan28** [comment]
@viditkothari You can close that PR that I have made...

**Comment by Kundan28** [comment]
I am making PR because may the changes that I have made can be used after making the design changes...

**Pull request closed without merging**
