### PR TITLE
Added 2 image files for banner (issue#1)

### PR DESCRIPTION
**Pull request by sainitripti**
Images for banner are added in public/assets/images with names img1.png and img2.png
Link to fork- https://github.com/sainitripti/jeevan-rakht.git

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @sainitripti,
Are these your original work?
And I can't see a major difference b/w the two? :sweat_smile: 
If you're interested in doing editing, etc, you may refer to : https://www.canva.com/
Meanwhile, I'm closing this as we'd much appreciate if the work is original. Please revert if you're interested to work on this or have issues regarding the same.
Looking forward for your participation.

**Comment by sainitripti5** [comment]
Hey @utkarsh2102 , 
These are my original work. I have used gimp to create this banner.
Also, both of the images are similar. They have a subtle difference. I have used a blood drop behind text in one and a heart in another.

**Comment by utkarsh2102** [comment]
Okay @sainitripti.
I'm reopening your PR.
@viditkothari @strongSoda @mcashashankkumar @gauravsinghaec @Soumya44 : Please review and comment.

**Comment by utkarsh2102** [comment]
Well, I'm not sure about the usage presently, but considering your original work, I'm merging the same.
I hope this comes handy in our upcoming phase.

**Comment by viditkothari** [comment]
@sainitripti 
these ([designs](https://github.com/sainitripti/jeevan-rakht/blob/b2774bdff273eec1d512c2a1d14b1f882ab94b0c/public/assets/images/img1.png)) are sized at ~19MB. That's **tooooooo** big. Although this has been merged, I'll suggest you to get any designs reviewed before creating a PR.

**Pull request merged**
