### PR TITLE
404 Error Page Styled

### PR DESCRIPTION
**Pull request by Ckbhatia**
Main Changes That I made !
404.hjs modified for styling Background for Separate Mobile View & Desktop View .
Image File added to Public assets 
app.css modified for best design on different gadget ...

// Next //
I am working already on more Creative page for this , it will take time .
so for that this for now . Most Code is ready for my future changes in this latest pull request ...

Thanks

### CODE REVIEW

**Comment by Ckbhatia** [comment]
@utlarsh , It's for App . But Content also Support Website as well .

**Comment by utkarsh2102** [comment]
@gauravsinghaec : Review it please :D

**Comment by gauravsinghaec** [comment]
@Ckbhatia please share the heroku link of your deployed app to check it.

**Comment by gauravsinghaec** [comment]
@Ckbhatia also please do not overwrite the existing code rather update it. As of your current code, it is difficult to merge as I see lot of changes in app.css (removing and adding same code which happens only if you overwrite the code without synching it with original repo or you edited the whole thing).
Also we are using partials(refer to README to know more) block of HTML for head, header, footer and common js links which was removed by your 404.hjs I can predict same reasoning for this as well.
Please sync your repo, check and update only the part you worked on. Thanks again.

**Comment by manasasravanthi96** [comment]
I have an idea of creating login page and verifing that entered email is
valid or not. For that I am sending a PR.
https://frontendindiascholars.slack.com/files/UA3A8330F/FAK004QE9/img_20180505_100337.jpg

**Comment by gauravsinghaec** [comment]
sorry @manasasravanthi96 the login and signup pages are done. You can check the app. We won't be having login and signup separate for website. Request you to check the app page. https://jeevanrakht.herokuapp.com/login
https://jeevanrakht.herokuapp.com/signup

**Comment by manasasravanthi96** [comment]
We I gone through the app in home page the Locate blood is having an issue
the back buttuon in not working. Can I modify that error.
https://jeevanrakht.herokuapp.com/locate

**Comment by gauravsinghaec** [comment]
@manasasravanthi96 please check the open issues. It is being taken care by someone already..

**Pull request closed without merging**
