### PR TITLE
adding logo for footer

### PR DESCRIPTION
**Pull request by webpagearshi**

### CODE REVIEW

**Comment by webpagearshi** [comment]
Hi @utkarsh2102 ,
I have added a footer-logo design in the assets/images folder .
footer-logo

**Comment by webpagearshi** [comment]
Hi @utkarsh2102,
I am adding an image for the footer-logo.I have added the image in the assets/images folder.
Here is the page review: https://webpagearshi.github.io/jeevan-rakht/public/assets/images/footer-logo.PNG

**Comment by utkarsh2102** [comment]
@webpagearshi,
Please implement the footer logo. And give a page preview of the same.
And only use it if it's original.

**Comment by webpagearshi** [comment]
Hi Vidit, I have added the content files but they have been added to the previous PR.

**Pull request merged**
