### PR TITLE
Locate page with responsive design added

### PR DESCRIPTION
**Pull request by creatorisback**
See screenshots for review
choose page
choose page1

### CODE REVIEW

**Comment by viditkothari** [comment]
@creatorisback as conveyed on slack, please make the adjustments before a PR.
thanks :)

**Comment by creatorisback** [comment]
Updated

**Comment by creatorisback** [comment]
It had no conflicts when i published changes @viditkothari this is what i was talking about.

**Comment by creatorisback** [comment]
Fonts Updated

**Comment by creatorisback** [comment]
Please merge see above commits for the detailed description of tasks

**Comment by creatorisback** [comment]
Conflicts resolved and footer updated ...Please merge

**Comment by gauravsinghaec** [comment]
Look into other .hjs files e.g views/auth/login.hjs...

**Pull request merged**
