### PR TITLE
#151 added blood_donate logo in footer

### PR DESCRIPTION
**Pull request by sskanishk**
screen shot 2018-04-30 at 10 52 00 am

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @sskanishk,
Please resolve merge conflict.

**Comment by sskanishk** [comment]
@utkarsh2102  Done!

**Comment by viditkothari** [comment]
@sskanishk the graphic looks good and attractive but please avid using *logo* for all such graphics. I know few others have used the term but it hurts a designer's feeling to hear people using the term logo casually :D

**Comment by sskanishk** [comment]
@viditkothari 
Plz suggest me..
It need some changes or design new n different graphic?

**Comment by mcashashankkumar** [comment]
@sskanishk  I appreciate your hard work and your graphics is so attractive.
But I agree with @viditkothari 
Plz I would like to suggest you contact with @viditkothari .

**Pull request closed without merging**
