### PR TITLE
Improved hamburger and sidebar

### PR DESCRIPTION
**Pull request by Vicks1010**
1. The `main.css` file was split into two, `main.css` and `sidebar.css`. It is was necessary, as the changes made to main.css during implementation of hamburger (#103) had some effects on other HTML files. The pages started to have boxes before Home and About on `login.html`, `profile.html` and `signup.html` (screenshot included).

2. Linked`sidebar.css` to `index.html`.

3. Some improvements in `main.js` for navbar and hamburger.

hamburger
##### PS: GitHub gives me a warning (Can’t automatically merge), but failed to find the reason.

### CODE REVIEW

**Comment by viditkothari** [comment]
@Soumya44 please review this and do the needful ASAP

**Comment by Vicks1010** [comment]
@viditkothari, @Soumya44

Conflict with `public/index.html` can be resolved, as the only addition made was the link for new CSS file created. The merge conflict came due to pull request #98, where the `index.html` was changed (check [line 31](https://github.com/UdacityFrontEndScholarship/jeevan-rakht/blob/fc8d8d4d2e75583fae64b0a2a505930d23eb44fe/public/index.html#L31) of `index.html`).

No idea for other conflict. Will let you know if found something.
Hope this helps :smile:

**Comment by Soumya44** [comment]
Sorry for the late review. Please resolve the conflicts and again raise a PR. Thanks

**Comment by Vicks1010** [comment]
The conflict with `index.html` can be ignored safely and merged. Will require your guidance/help to resolve the conflict with `main.css`. Tried updating my branch, but it didn't help.

**Pull request closed without merging**
