### PR TITLE
Added image file 

### PR DESCRIPTION
**Pull request by Kundan28**
Fix issue-1 
Added image file for banner in public/assets/image folder with name img1 and extension .jpg
Fork link
https://github.com/Kundan28/jeevan-rakht

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Hi @Kundan28,
We need more of it. Not just one. And please try to make one yourself.
You may use https://www.canva.com/ for the same.
And please update here as soon as you're done.

**Comment by Kundan28** [comment]
Hi @utkarsh2102 
The image that I uploaded is up to the mark or not ?

**Comment by utkarsh2102** [comment]
@Kundan28, was it your own editing? Your own work?

**Comment by Kundan28** [comment]
I have only done some editing but the original image was not mine.

**Comment by utkarsh2102** [comment]
Could you please add your own work, because we don't want to be marked as "Plagiarism" for anything.
You can use https://www.canva.com for editing. 
Let me know if you're up for this task.
Since this is not an original image, I can't really merge the same for now.
Do let me know if you're interested to work on this?

**Comment by Kundan28** [comment]
@utkarsh2102  I am interested to work on that...

**Comment by utkarsh2102** [comment]
@Kundan28,
Great to hear that. Please create an issue and take up the task.

**Comment by Kundan28** [comment]
@utkarsh2102 But there already exist issue 1 that is same as I want, so should I create another issue or not ?

**Pull request closed without merging**
