### PR TITLE
app.html for #Issue-3

### PR DESCRIPTION
**Pull request by praveen-me**
Make full **app.html** and it's fully responsive.
If you feel there's any kind of bug or else that I don't take a look clearly just told me. 
I would fix that instantly.

### CODE REVIEW

**Comment by praveen-me** [comment]
Ok, Wait for sometime.

**Comment by praveen-me** [comment]
I add the gh-pages @utkarsh2102 .

**Comment by praveen-me** [comment]
You can also check it here: 
https://praveen-me.herokuapp.com/app.html

**Comment by utkarsh2102** [comment]
@praveen-me,
These changes looks good to me.
@strongSoda @viditkothari @gauravsinghaec @mcashashankkumar : Please add your reviews.
If we have a mutual consent on this, we can merge this.

**Comment by praveen-me** [comment]
Thanks @utkarsh2102 .

**Comment by gauravsinghaec** [comment]
Please check the new files as app.ht,l is removed from the folder and also it is finalized now. Please check /views/app.hjs file

**Pull request closed without merging**
