### PR TITLE
Imp/index laptop

### PR DESCRIPTION
**Pull request by Vicks1010**
The logo in `index.html` was not center aligned. Also, for Laptops with MiPDI screen, the `How to Donate?` would split into into parts. Screenshots are included below for reference.
Made changes to `bin/www` so that when we run `heroku local`, the web server is opened.

jeevanrakht herokuapp com_index html laptop with mdpi screen
localhost_5000_index html laptop with hidpi screen

### CODE REVIEW

**Comment by Vicks1010** [comment]
The changes made to `bin/www` only opens a new tab in your default browser, thus directing you to your web server (in my case, http://localhost:5000). The opn package is already available in node_modules. But if you still insist, I'll revert the changes :smiley:
PS: I have no problem running the app locally with heroku

**Comment by gauravsinghaec** [comment]
Okay.. @Vicks1010 did you raise an issue before making PR? or if it is related to any issues then please comment on that issue and get the confirmation before making PR. Sorry but it will help us if you stick to the guidelines as mentioned in README. Also, share the working link on the issue as well.

**Comment by Vicks1010** [comment]
@gauravsinghaec Thanks for reviewing. Since it was a small improvement, I didn't raise any issue. I'll keep that in mind for future PRs. The first screenshot is of the issue, and the second screenshot is of the working page. [Heroku link ](https://vicks1010.herokuapp.com/index.html)for `index.html`

**Comment by gauravsinghaec** [comment]
@Vicks1010 please open an issue and share with us there. Also you changes should go hand in had with mobile version too. Check that on your heroku link otherwise job is like half done. We are looking forward for your issues with these changes. 👍

**Pull request closed without merging**
